#!/usr/bin/env python
#coding:gbk 
#Copyright (c) Baidu.com, Inc. All Rights Reserved 
#author:zhangyan04(@baidu.com)

def rev(s):
    ns = ''
    for x in s:
        ns = x + ns
    return ns

import sys
sys.stdout=open('ul_url2_inl.cc','w')

print "// generated by 'suffix.py' DONT try to edit it"

print """struct domain_map_entry {
  const char* top_domain;
  const char** second_domain;
}; """

L = []
d = {}
for x in open('suffix.txt').readlines():
    if(x and x[0]=='#'):
        continue
    y = x.split()
    for z in y:        
        z2 = z.split('.')[1]
        if z2 in d:
            d[z2].append(z)
        else:
            d[z2]=[z]

for (z,y) in d.items():    
    L.append(z)
    print 'static const char* %(z)s_domain[] = {'%(locals())
    for z in y:
        z = '.' + z
        z = rev(z)
        print '"%(z)s",'%(locals())
    print '0\n};'
print '\n'

print 'static domain_map_entry domain_map [] = {'
for x in L:
    z = '.' + x
    z = rev(z)
    print '{"%(z)s", %(x)s_domain},'%(locals())
print '{0,0}\n};'
