// generated by 'suffix.py' DONT try to edit it
struct domain_map_entry {
  const char* top_domain;
  const char** second_domain;
}; 
static const char* gt_domain[] = {
"tg.bog.",
"tg.dni.",
0
};
static const char* gp_domain[] = {
"pg.ossa.",
0
};
static const char* gg_domain[] = {
"gg.ca.",
"gg.yenredla.",
"gg.oc.",
"gg.yesnreug.",
"gg.dni.",
"gg.dtl.",
"gg.kras.",
"gg.hcs.",
0
};
static const char* ge_domain[] = {
"eg.tvp.",
0
};
static const char* gn_domain[] = {
"ng.ca.",
0
};
static const char* gi_domain[] = {
"ig.dtl.",
"ig.dom.",
0
};
static const char* tz_domain[] = {
"zt.ca.",
"zt.oc.",
"zt.og.",
"zt.en.",
"zt.ro.",
0
};
static const char* tn_domain[] = {
"nt.tenude.",
"nt.sne.",
"nt.nif.",
"nt.dni.",
"nt.ltni.",
"nt.tan.",
"nt.trnr.",
"nt.snr.",
"nt.unr.",
"nt.msiruot.",
0
};
static const char* tv_domain[] = {
"vt.oc.",
0
};
static const char* tw_domain[] = {
"wt.bulc.",
"wt.zibe.",
"wt.emag.",
"wt.vdi.",
0
};
static const char* tt_domain[] = {
"tt.ta.",
"tt.ua.",
"tt.eb.",
"tt.ac.",
"tt.oc.",
"tt.ed.",
"tt.kd.",
"tt.se.",
"tt.ue.",
"tt.rf.",
"tt.ti.",
"tt.cin.",
"tt.es.",
"tt.ku.",
"tt.su.",
0
};
static const char* arpa_domain[] = {
"apra.461e.",
"apra.rdda-ni.",
"apra.6pi.",
"apra.siri.",
"apra.iru.",
"apra.nru.",
0
};
static const char* lk_domain[] = {
"kl.nssa.",
"kl.prg.",
"kl.letoh.",
"kl.dtl.",
"kl.ogn.",
"kl.hcs.",
"kl.cos.",
"kl.bew.",
0
};
static const char* lv_domain[] = {
"vl.nsa.",
"vl.fnoc.",
"vl.di.",
0
};
static const char* tj_domain[] = {
"jt.ca.",
"jt.oc.",
"jt.og.",
"jt.bew.",
0
};
static const char* ls_domain[] = {
"sl.oc.",
0
};
static const char* th_domain[] = {
"ht.ca.",
"ht.oc.",
"ht.og.",
"ht.ni.",
"ht.im.",
"ht.ro.",
0
};
static const char* tf_domain[] = {
"ft.ta.",
"ft.gb.",
"ft.ac.",
"ft.hc.",
"ft.zc.",
"ft.ed.",
"ft.ue.",
"ft.lp.",
"ft.ur.",
"ft.gs.",
"ft.su.",
0
};
static const char* ly_domain[] = {
"yl.di.",
"yl.dem.",
"yl.clp.",
"yl.hcs.",
0
};
static const char* do_domain[] = {
"od.tra.",
"od.bog.",
"od.dls.",
"od.bew.",
0
};
static const char* dk_domain[] = {
"kd.oc.",
0
};
static const char* dz_domain[] = {
"zd.tra.",
"zd.ossa.",
"zd.lop.",
0
};
static const char* uy_domain[] = {
"yu.bug.",
0
};
static const char* vu_domain[] = {
"uv.hc.",
"uv.ed.",
"uv.rf.",
0
};
static const char* zm_domain[] = {
"mz.ca.",
"mz.oc.",
"mz.hcs.",
0
};
static const char* ee_domain[] = {
"ee.oc.",
"ee.eif.",
"ee.dem.",
"ee.irp.",
0
};
static const char* eg_domain[] = {
"ge.nue.",
"ge.ics.",
0
};
static const char* za_domain[] = {
"az.ca.",
"az.tla.",
"az.esruob.",
"az.ytic.",
"az.oc.",
"az.wal.",
"az.ogn.",
"az.mon.",
"az.loohcs.",
"az.mt.",
"az.bew.",
0
};
static const char* ec_domain[] = {
"ce.nif.",
"ce.21k.",
"ce.dem.",
0
};
static const char* zw_domain[] = {
"wz.ca.",
"wz.oc.",
0
};
static const char* es_domain[] = {
"se.bog.",
"se.mon.",
0
};
static const char* er_domain[] = {
"re.dni.",
0
};
static const char* ru_domain[] = {
"ur.ca.",
"ur.ayegyda.",
"ur.iatla.",
"ur.ruma.",
"ur.ksruma.",
"ur.kslegnahkra.",
"ur.nahkartsa.",
"ur.lakiab.",
"ur.airikhsab.",
"ur.dorogleb.",
"ur.rib.",
"ur.ksnayrb.",
"ur.aitayrub.",
"ur.gbc.",
"ur.lehc.",
"ur.ksnibaylehc.",
"ur.atihc.",
"ur.aktokuhc.",
"ur.aihsavuhc.",
"ur.wmc.",
"ur.natsegad.",
"ur.aknidud.",
"ur.grub-e.",
"ur.tsaeraf.",
"ur.ynzorg.",
"ur.kstukri.",
"ur.ovonavi.",
"ur.ksvehzi.",
"ur.lamaj.",
"ur.raj.",
"ur.alo-rakhsoj.",
"ur.kslaru-k.",
"ur.aikymlak.",
"ur.agulak.",
"ur.aktahcmak.",
"ur.ailerak.",
"ur.nazak.",
"ur.rhck.",
"ur.ovoremek.",
"ur.ksvorabahk.",
"ur.aissakahk.",
"ur.vhk.",
"ur.vorik.",
"ur.smk.",
"ur.gineok.",
"ur.imok.",
"ur.amortsok.",
"ur.ksrayonsark.",
"ur.nabuk.",
"ur.nagruk.",
"ur.ksruk.",
"ur.ianatsuk.",
"ur.ssabzuk.",
"ur.kstepil.",
"ur.nadagam.",
"ur.aktingam.",
"ur.le-iram.",
"ur.iram.",
"ur.eniram.",
"ur.aivodrom.",
"ur.gersom.",
"ur.ksm.",
"ur.ksnamrum.",
"ur.sitym.",
"ur.akdohkan.",
"ur.kihclan.",
"ur.zkn.",
"ur.vonn.",
"ur.ksliron.",
"ur.von.",
"ur.ksribisovon.",
"ur.ksn.",
"ur.ksmo.",
"ur.grubnero.",
"ur.loyro.",
"ur.lokso.",
"ur.analap.",
"ur.aznep.",
"ur.mrep.",
"ur.pp.",
"ur.voksp.",
"ur.ztp.",
"ur.ksrogitayp.",
"ur.dnr.",
"ur.ksvostbur.",
"ur.nazayr.",
"ur.nilahkas.",
"ur.aramas.",
"ur.votaras.",
"ur.ksribmis.",
"ur.ksneloms.",
"ur.zns.",
"ur.bps.",
"ur.loporvats.",
"ur.vts.",
"ur.tugrus.",
"ur.narzys.",
"ur.vobmat.",
"ur.natsratat.",
"ur.tset.",
"ur.mot.",
"ur.ksmot.",
"ur.nystirast.",
"ur.kst.",
"ur.alut.",
"ur.avut.",
"ur.revt.",
"ur.nemuyt.",
"ur.mdu.",
"ur.aitrumdu.",
"ur.edu-nalu.",
"ur.ksnodv.",
"ur.zakvakidalv.",
"ur.rimidalv.",
"ur.kotsovidalv.",
"ur.dargoglov.",
"ur.adgolov.",
"ur.hzenorov.",
"ur.nrv.",
"ur.aktayv.",
"ur.aitukay.",
"ur.lamay.",
"ur.lvalsoray.",
"ur.grubniretakey.",
"ur.ksnilahkas-onhzuy.",
"ur.dargz.",
0
};
static const char* rw_domain[] = {
"wr.ca.",
"wr.oc.",
"wr.vuog.",
0
};
static const char* rs_domain[] = {
"sr.ca.",
"sr.oc.",
"sr.ni.",
0
};
static const char* re_domain[] = {
"er.ossa.",
"er.mon.",
0
};
static const char* net_domain[] = {
"ten.ed.",
"ten.bg.",
"ten.ku.",
0
};
static const char* ro_domain[] = {
"or.stra.",
"or.mrif.",
"or.mon.",
"or.tn.",
"or.cer.",
"or.erots.",
"or.mt.",
"or.www.",
0
};
static const char* bd_domain[] = {
"db.ca.",
0
};
static const char* be_domain[] = {
"eb.ca.",
"eb.eigleb.",
"eb.snd.",
"eb.vogf.",
0
};
static const char* ba_domain[] = {
"ab.oc.",
"ab.sr.",
"ab.ibnu.",
"ab.asnu.",
0
};
static const char* bh_domain[] = {
"hb.cc.",
0
};
static const char* bo_domain[] = {
"ob.bog.",
"ob.vt.",
0
};
static const char* jp_domain[] = {
"pj.ca.",
"pj.da.",
"pj.ihcia.",
"pj.atika.",
"pj.iromoa.",
"pj.abihc.",
"pj.oc.",
"pj.de.",
"pj.emihe.",
"pj.iukuf.",
"pj.akoukuf.",
"pj.amihsukuf.",
"pj.ufig.",
"pj.og.",
"pj.rg.",
"pj.amnug.",
"pj.amihsorih.",
"pj.odiakkoh.",
"pj.ogoyh.",
"pj.ikarabi.",
"pj.awakihsi.",
"pj.etawi.",
"pj.awagak.",
"pj.amihsogak.",
"pj.awaganak.",
"pj.awazanak.",
"pj.ikasawak.",
"pj.uhsuykatik.",
"pj.ebok.",
"pj.ihcok.",
"pj.otomamuk.",
"pj.otoyk.",
"pj.gl.",
"pj.amayustam.",
"pj.eim.",
"pj.igayim.",
"pj.ikazayim.",
"pj.onagan.",
"pj.ikasagan.",
"pj.ayogan.",
"pj.aran.",
"pj.en.",
"pj.atagiin.",
"pj.atio.",
"pj.amayako.",
"pj.awaniko.",
"pj.ro.",
"pj.akaso.",
"pj.agas.",
"pj.amatias.",
"pj.oroppas.",
"pj.iadnes.",
"pj.agihs.",
"pj.enamihs.",
"pj.akouzihs.",
"pj.ustamakat.",
"pj.igihcot.",
"pj.amihsukot.",
"pj.oykot.",
"pj.irottot.",
"pj.amayot.",
"pj.ayimonustu.",
"pj.amayakaw.",
"pj.atagamay.",
"pj.ihcugamay.",
"pj.ihsanamay.",
"pj.amahokoy.",
0
};
static const char* bw_domain[] = {
"wb.oc.",
0
};
static const char* br_domain[] = {
"rb.mda.",
"rb.vda.",
"rb.rga.",
"rb.ma.",
"rb.qra.",
"rb.tra.",
"rb.ota.",
"rb.oib.",
"rb.dmb.",
"rb.mic.",
"rb.gnc.",
"rb.tnc.",
"rb.npd.",
"rb.nce.",
"rb.gne.",
"rb.pse.",
"rb.cte.",
"rb.ite.",
"rb.raf.",
"rb.mf.",
"rb.dnf.",
"rb.tof.",
"rb.tsf.",
"rb.21g.",
"rb.fgg.",
"rb.bmi.",
"rb.dni.",
"rb.fni.",
"rb.roj.",
"rb.lel.",
"rb.tam.",
"rb.dem.",
"rb.sum.",
"rb.mon.",
"rb.ton.",
"rb.rtn.",
"rb.odo.",
"rb.gpp.",
"rb.csp.",
"rb.isp.",
"rb.lsq.",
"rb.cer.",
"rb.gls.",
"rb.vrs.",
"rb.pmt.",
"rb.drt.",
"rb.rut.",
"rb.vt.",
"rb.tev.",
"rb.glz.",
0
};
static const char* org_domain[] = {
"gro.kd.",
"gro.ue.",
0
};
static const char* om_domain[] = {
"mo.ca.",
"mo.oc.",
"mo.dem.",
"mo.dom.",
"mo.hcs.",
0
};
static const char* ck_domain[] = {
"kc.oc.",
0
};
static const char* co_domain[] = {
"oc.stra.",
"oc.mrif.",
"oc.mon.",
"oc.cer.",
"oc.erots.",
"oc.bew.",
"mi.oc.dkl.",
"mi.oc.dtl.",
"mi.oc.clp.",
0
};
static const char* cn_domain[] = {
"nc.ca.",
"nc.ha.",
"nc.jb.",
"nc.qc.",
"nc.jf.",
"nc.dg.",
"nc.sg.",
"nc.xg.",
"nc.zg.",
"nc.ah.",
"nc.bh.",
"nc.eh.",
"nc.ih.",
"nc.kh.",
"nc.lh.",
"nc.nh.",
"nc.lj.",
"nc.sj.",
"nc.xj.",
"nc.nl.",
"nc.om.",
"nc.mn.",
"nc.xn.",
"nc.hq.",
"nc.cs.",
"nc.ds.",
"nc.hs.",
"nc.ns.",
"nc.xs.",
"nc.jt.",
"nc.wt.",
"nc.jx.",
"nc.zx.",
"nc.ny.",
"nc.jz.",
0
};
static const char* tr_domain[] = {
"rt.va.",
"rt.sbb.",
"rt.leb.",
"rt.rd.",
"rt.neg.",
"rt.21k.",
"rt.lop.",
"rt.bew.",
0
};
static const char* ca_domain[] = {
"ac.ba.",
"ac.cb.",
"ac.cg.",
"ac.bm.",
"ac.bn.",
"ac.fn.",
"ac.ln.",
"ac.sn.",
"ac.tn.",
"ac.un.",
"ac.no.",
"ac.ep.",
"ac.cq.",
"ac.ks.",
"ac.ky.",
0
};
static const char* cy_domain[] = {
"yc.ca.",
"yc.segolke.",
"yc.dtl.",
"yc.tnemailrap.",
"yc.sserp.",
"yc.mt.",
0
};
static const char* je_domain[] = {
"ej.ca.",
"ej.oc.",
"ej.dni.",
"ej.yesrej.",
"ej.dtl.",
"ej.hcs.",
0
};
static const char* cr_domain[] = {
"rc.ca.",
"rc.oc.",
"rc.de.",
"rc.if.",
"rc.og.",
"rc.ro.",
"rc.as.",
0
};
static const char* cu_domain[] = {
"uc.fni.",
0
};
static const char* ve_domain[] = {
"ev.stra.",
"ev.bib.",
"ev.oc.",
"ev.mrif.",
"ev.mon.",
"ev.cer.",
"ev.erots.",
"ev.cet.",
"ev.bew.",
0
};
static const char* pr_domain[] = {
"rp.alsi.",
0
};
static const char* ps_domain[] = {
"sp.olp.",
"sp.ces.",
0
};
static const char* pt_domain[] = {
"tp.emon.",
"tp.lbup.",
0
};
static const char* pa_domain[] = {
"ap.oba.",
"ap.ca.",
"ap.bog.",
"ap.gni.",
"ap.dem.",
"ap.mon.",
"ap.dls.",
0
};
static const char* pg_domain[] = {
"gp.ca.",
0
};
static const char* pe_domain[] = {
"ep.bog.",
"ep.mon.",
0
};
static const char* pk_domain[] = {
"kp.maf.",
"kp.bog.",
"kp.kog.",
"kp.nog.",
"kp.pog.",
"kp.sog.",
"kp.bew.",
0
};
static const char* ph_domain[] = {
"hp.ogn.",
0
};
static const char* pl_domain[] = {
"lp.orga.",
"lp.dia.",
"lp.tra.",
"lp.mta.",
"lp.otua.",
"lp.kotsylaib.",
"lp.adg.",
"lp.ksnadg.",
"lp.animg.",
"lp.msg.",
"lp.eciwotak.",
"lp.wokark.",
"lp.zdol.",
"lp.nilbul.",
"lp.liam.",
"lp.aidem.",
"lp.atsaim.",
"lp.ogn.",
"lp.icsomohcurein.",
"lp.mon.",
"lp.nytzslo.",
"lp.elopo.",
"lp.cp.",
"lp.taiwop.",
"lp.nanzop.",
"lp.virp.",
"lp.etatselaer.",
"lp.ler.",
"lp.xes.",
"lp.pohs.",
"lp.pelks.",
"lp.kspuls.",
"lp.sos.",
"lp.nicezczs.",
"lp.alokzs.",
"lp.igrat.",
"lp.mt.",
"lp.nurot.",
"lp.msiruot.",
"lp.akytsyrut.",
"lp.awazsraw.",
"lp.waw.",
"lp.corw.",
"lp.walcorw.",
"lp.az.",
"lp.arogz.",
0
};
static const char* hr_domain[] = {
"rh.morf.",
"rh.zi.",
0
};
static const char* ht_domain[] = {
"th.tluda.",
"th.tra.",
"th.ossa.",
"th.mrif.",
"th.vuog.",
"th.dem.",
"th.osrep.",
"th.lop.",
"th.ler.",
"th.pohs.",
0
};
static const char* hu_domain[] = {
"uh.0002.",
"uh.ca.",
"uh.rarga.",
"uh.tlob.",
"uh.onisac.",
"uh.ytic.",
"uh.oc.",
"uh.acitore.",
"uh.akitore.",
"uh.mlif.",
"uh.murof.",
"uh.semag.",
"uh.letoh.",
"uh.naltagni.",
"uh.zsagoj.",
"uh.olevynok.",
"uh.sakal.",
"uh.aidem.",
"uh.swen.",
"uh.virp.",
"uh.malker.",
"uh.xes.",
"uh.pohs.",
"uh.trops.",
"uh.ilus.",
"uh.xezs.",
"uh.mt.",
"uh.edszot.",
"uh.sazatu.",
"uh.oediv.",
0
};
static const char* hk_domain[] = {
"kh.vdi.",
0
};
static const char* hn_domain[] = {
"nh.bog.",
0
};
static const char* vn_domain[] = {
"nv.ca.",
"nv.htlaeh.",
0
};
static const char* me_domain[] = {
"em.ca.",
"em.oc.",
"em.sti.",
"em.virp.",
0
};
static const char* mg_domain[] = {
"gm.mon.",
"gm.drp.",
"gm.mt.",
0
};
static const char* ma_domain[] = {
"am.ca.",
"am.oc.",
"am.sserp.",
0
};
static const char* mc_domain[] = {
"cm.ossa.",
"cm.mt.",
0
};
static const char* us_domain[] = {
"su.ka.",
"su.la.",
"su.ra.",
"su.za.",
"su.ac.",
"su.oc.",
"su.tc.",
"su.cd.",
"su.ed.",
"su.ind.",
"su.def.",
"su.lf.",
"su.ag.",
"su.ih.",
"su.ai.",
"su.di.",
"su.li.",
"su.ni.",
"su.asi.",
"su.sdik.",
"su.sk.",
"su.yk.",
"su.al.",
"su.am.",
"su.dm.",
"su.em.",
"su.im.",
"su.nm.",
"su.om.",
"su.sm.",
"su.tm.",
"su.cn.",
"su.dn.",
"su.en.",
"su.hn.",
"su.jn.",
"su.mn.",
"su.nsn.",
"su.vn.",
"su.yn.",
"su.ho.",
"su.ko.",
"su.ro.",
"su.ap.",
"su.ir.",
"su.cs.",
"su.ds.",
"su.nt.",
"su.xt.",
"su.tu.",
"su.av.",
"su.tv.",
"su.aw.",
"su.iw.",
"su.vw.",
"su.yw.",
0
};
static const char* mu_domain[] = {
"um.oc.",
0
};
static const char* mt_domain[] = {
"tm.mt.",
"tm.uu.",
0
};
static const char* mw_domain[] = {
"wm.ca.",
"wm.oc.",
0
};
static const char* uk_domain[] = {
"ku.ca.",
"ku.lb.",
"ku.yrarbil-hsitirb.",
"ku.oc.",
"ku.tenci.",
"ku.tej.",
"ku.dtl.",
"ku.em.",
"ku.dom.",
"ku.dnaltocs-yrarbil-lanoitan.",
"ku.shn.",
"ku.cin.",
"ku.sln.",
"ku.tnemailrap.",
"ku.clp.",
"ku.ecilop.",
"ku.hcs.",
0
};
static const char* im_domain[] = {
"mi.ca.",
"mi.oc.",
"mi.cin.",
0
};
static const char* ug_domain[] = {
"gu.ca.",
"gu.oc.",
"gu.og.",
"gu.en.",
"gu.ro.",
"gu.cs.",
0
};
static const char* ua_domain[] = {
"au.yssakrehc.",
"au.voginrehc.",
"au.ystvonrehc.",
"au.kc.",
"au.nc.",
"au.oc.",
"au.aemirc.",
"au.vc.",
"au.nd.",
"au.ksvorteporpend.",
"au.kstenod.",
"au.pd.",
"au.fi.",
"au.ni.",
"au.ksviknarf-onavi.",
"au.hk.",
"au.vokrahk.",
"au.nosrehk.",
"au.yikstinlemhk.",
"au.veik.",
"au.dargovorik.",
"au.mk.",
"au.rk.",
"au.sk.",
"au.vk.",
"au.gl.",
"au.ksnagul.",
"au.kstul.",
"au.vivl.",
"au.km.",
"au.vealokin.",
"au.do.",
"au.assedo.",
"au.lp.",
"au.avatlop.",
"au.onvor.",
"au.vr.",
"au.lopotsabes.",
"au.ymus.",
"au.et.",
"au.liponret.",
"au.doroghzu.",
"au.acinniv.",
"au.nv.",
"au.ehzhziropaz.",
"au.rimotihz.",
"au.pz.",
"au.tz.",
0
};
static const char* mx_domain[] = {
"xm.bog.",
0
};
static const char* il_domain[] = {
"li.ca.",
"li.oc.",
"li.fdi.",
"li.21k.",
"li.inum.",
0
};
static const char* va_domain[] = {
"av.nacitav.",
0
};
static const char* ae_domain[] = {
"ea.ca.",
"ea.oc.",
"ea.hcs.",
0
};
static const char* ad_domain[] = {
"da.mon.",
0
};
static const char* ag_domain[] = {
"ga.oc.",
"ga.mon.",
0
};
static const char* ai_domain[] = {
"ia.ffo.",
0
};
static const char* vi_domain[] = {
"iv.oc.",
0
};
static const char* pro_domain[] = {
"orp.apc.",
"orp.wal.",
"orp.dem.",
0
};
static const char* ir_domain[] = {
"ri.ca.",
"ri.oc.",
"ri.di.",
"ri.hcs.",
0
};
static const char* ao_domain[] = {
"oa.oc.",
"oa.de.",
"oa.vg.",
"oa.ti.",
"oa.go.",
"oa.bp.",
0
};
static const char* au_domain[] = {
"ua.tca.",
"ua.nsa.",
"ua.fnoc.",
"ua.orisc.",
"ua.di.",
"ua.wsn.",
"ua.tn.",
"ua.cto.",
"ua.zo.",
"ua.dlq.",
"ua.as.",
"ua.sat.",
"ua.omemelet.",
"ua.civ.",
"ua.aw.",
0
};
static const char* at_domain[] = {
"ta.ca.",
"ta.oc.",
"ta.vg.",
"ta.ro.",
"ta.virp.",
0
};
static const char* in_domain[] = {
"ni.ca.",
"ni.oc.",
"ni.tenre.",
"ni.mrif.",
"ni.neg.",
"ni.dni.",
"ni.cin.",
"ni.ser.",
0
};
static const char* az_domain[] = {
"za.pp.",
0
};
static const char* id_domain[] = {
"di.ca.",
"di.oc.",
"di.og.",
"di.ro.",
"di.hcs.",
"di.bew.",
0
};
static const char* ni_domain[] = {
"in.bog.",
"in.mon.",
0
};
static const char* mil_domain[] = {
"lim.ymra.",
"lim.yvan.",
0
};
static const char* no_domain[] = {
"on.shf.",
"on.lbibeklof.",
"on.lbibseklyf.",
"on.dareh.",
"on.tterdi.",
"on.enummok.",
"on.virp.",
"on.tats.",
"on.sgv.",
0
};
static const char* na_domain[] = {
"an.tla.",
"an.luc.",
"an.mocelet.",
"an.manu.",
0
};
static const char* ng_domain[] = {
"gn.ca.",
"gn.hcs.",
0
};
static const char* nz_domain[] = {
"zn.ca.",
"zn.oc.",
"zn.irc.",
"zn.keeg.",
"zn.neg.",
"zn.tvog.",
"zn.iwi.",
"zn.iroam.",
"zn.loohcs.",
"zn.tnemailrap.",
0
};
static const char* nr_domain[] = {
"rn.oc.",
"rn.xaf.",
"rn.bom.",
"rn.libom.",
"rn.elibom.",
"rn.flt.",
0
};
static const char* fr_domain[] = {
"rf.troporea.",
"rf.cidessa.",
"rf.ossa.",
"rf.tacova.",
"rf.seuova.",
"rf.uaerrab.",
"rf.icc.",
"rf.irgabmahc.",
"rf.setsitned-sneigrurihc.",
"rf.selbatpmoc-strepxe.",
"rf.trepxe-ertemoeg.",
"rf.vuog.",
"rf.aterg.",
"rf.ecitsuj-reissiuh.",
"rf.nicedem.",
"rf.mon.",
"rf.seriaton.",
"rf.neicamrahp.",
"rf.trop.",
"rf.drp.",
"rf.esserp.",
"rf.mt.",
"rf.erianiretev.",
0
};
static const char* fi_domain[] = {
"if.dnala.",
0
};
static const char* fj_domain[] = {
"jf.ca.",
"jf.di.",
"jf.loohcs.",
0
};
static const char* fk_domain[] = {
"kf.ca.",
"kf.oc.",
"kf.mon.",
0
};
static const char* mobi_domain[] = {
"ibom.cisum.",
"ibom.rehtaew.",
0
};
static const char* ke_domain[] = {
"ek.ca.",
"ek.oc.",
"ek.og.",
"ek.en.",
"ek.wen.",
"ek.ro.",
"ek.cs.",
0
};
static const char* kh_domain[] = {
"hk.rep.",
0
};
static const char* sv_domain[] = {
"vs.bog.",
"vs.der.",
0
};
static const char* st_domain[] = {
"ts.oc.",
"ts.odalusnoc.",
"ts.adaxiabme.",
"ts.epicnirp.",
"ts.emotoas.",
"ts.erots.",
0
};
static const char* kr_domain[] = {
"rk.ca.",
"rk.nasub.",
"rk.kubgnuhc.",
"rk.mangnuhc.",
"rk.oc.",
"rk.ugead.",
"rk.noejead.",
"rk.se.",
"rk.nowgnag.",
"rk.og.",
"rk.ujgnawg.",
"rk.kubgnoeyg.",
"rk.iggnoeyg.",
"rk.mangnoeyg.",
"rk.sh.",
"rk.noehcni.",
"rk.ujej.",
"rk.kubnoej.",
"rk.mannoej.",
"rk.gk.",
"rk.iggnoyk.",
"rk.sm.",
"rk.en.",
"rk.ro.",
"rk.ep.",
"rk.er.",
"rk.cs.",
"rk.luoes.",
"rk.naslu.",
0
};
static const char* sa_domain[] = {
"as.dem.",
"as.bup.",
"as.hcs.",
0
};
static const char* sg_domain[] = {
"gs.ndi.",
"gs.rep.",
0
};
static const char* se_domain[] = {
"es.ba.",
"es.ca.",
"es.db.",
"es.dnarb.",
"es.c.",
"es.d.",
"es.e.",
"es.f.",
"es.hf.",
"es.kshf.",
"es.vhf.",
"es.g.",
"es.h.",
"es.i.",
"es.k.",
"es.brofmok.",
"es.dnubroflanummok.",
"es.xuvmok.",
"es.branal.",
"es.bibnal.",
"es.m.",
"es.n.",
"es.nmygskurbrutan.",
"es.o.",
"es.itrap.",
"es.pp.",
"es.sserp.",
"es.s.",
"es.nhss.",
"es.t.",
"es.mt.",
"es.u.",
"es.w.",
"es.x.",
"es.y.",
"es.z.",
0
};
static const char* sd_domain[] = {
"ds.dem.",
"ds.hcs.",
"ds.vt.",
0
};


static domain_map_entry domain_map [] = {
{"tg.", gt_domain},
{"pg.", gp_domain},
{"gg.", gg_domain},
{"eg.", ge_domain},
{"ng.", gn_domain},
{"ig.", gi_domain},
{"zt.", tz_domain},
{"nt.", tn_domain},
{"vt.", tv_domain},
{"wt.", tw_domain},
{"tt.", tt_domain},
{"apra.", arpa_domain},
{"kl.", lk_domain},
{"vl.", lv_domain},
{"jt.", tj_domain},
{"sl.", ls_domain},
{"ht.", th_domain},
{"ft.", tf_domain},
{"yl.", ly_domain},
{"od.", do_domain},
{"kd.", dk_domain},
{"zd.", dz_domain},
{"yu.", uy_domain},
{"uv.", vu_domain},
{"mz.", zm_domain},
{"ee.", ee_domain},
{"ge.", eg_domain},
{"az.", za_domain},
{"ce.", ec_domain},
{"wz.", zw_domain},
{"se.", es_domain},
{"re.", er_domain},
{"ur.", ru_domain},
{"wr.", rw_domain},
{"sr.", rs_domain},
{"er.", re_domain},
{"ten.", net_domain},
{"or.", ro_domain},
{"db.", bd_domain},
{"eb.", be_domain},
{"ab.", ba_domain},
{"hb.", bh_domain},
{"ob.", bo_domain},
{"pj.", jp_domain},
{"wb.", bw_domain},
{"rb.", br_domain},
{"gro.", org_domain},
{"mo.", om_domain},
{"kc.", ck_domain},
{"oc.", co_domain},
{"nc.", cn_domain},
{"rt.", tr_domain},
{"ac.", ca_domain},
{"yc.", cy_domain},
{"ej.", je_domain},
{"rc.", cr_domain},
{"uc.", cu_domain},
{"ev.", ve_domain},
{"rp.", pr_domain},
{"sp.", ps_domain},
{"tp.", pt_domain},
{"ap.", pa_domain},
{"gp.", pg_domain},
{"ep.", pe_domain},
{"kp.", pk_domain},
{"hp.", ph_domain},
{"lp.", pl_domain},
{"rh.", hr_domain},
{"th.", ht_domain},
{"uh.", hu_domain},
{"kh.", hk_domain},
{"nh.", hn_domain},
{"nv.", vn_domain},
{"em.", me_domain},
{"gm.", mg_domain},
{"am.", ma_domain},
{"cm.", mc_domain},
{"su.", us_domain},
{"um.", mu_domain},
{"tm.", mt_domain},
{"wm.", mw_domain},
{"ku.", uk_domain},
{"mi.", im_domain},
{"gu.", ug_domain},
{"au.", ua_domain},
{"xm.", mx_domain},
{"li.", il_domain},
{"av.", va_domain},
{"ea.", ae_domain},
{"da.", ad_domain},
{"ga.", ag_domain},
{"ia.", ai_domain},
{"iv.", vi_domain},
{"orp.", pro_domain},
{"ri.", ir_domain},
{"oa.", ao_domain},
{"ua.", au_domain},
{"ta.", at_domain},
{"ni.", in_domain},
{"za.", az_domain},
{"di.", id_domain},
{"in.", ni_domain},
{"lim.", mil_domain},
{"on.", no_domain},
{"an.", na_domain},
{"gn.", ng_domain},
{"zn.", nz_domain},
{"rn.", nr_domain},
{"rf.", fr_domain},
{"if.", fi_domain},
{"jf.", fj_domain},
{"kf.", fk_domain},
{"ibom.", mobi_domain},
{"ek.", ke_domain},
{"hk.", kh_domain},
{"vs.", sv_domain},
{"ts.", st_domain},
{"rk.", kr_domain},
{"as.", sa_domain},
{"gs.", sg_domain},
{"es.", se_domain},
{"ds.", sd_domain},
{0,0}
};
